osx_image: xcode9.2
language: objective-c
script:
- ./travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Use addon: instead of deploy:
# https://docs.travis-ci.com/user/uploading-artifacts/
addons:
  artifacts: true
