osx_image: xcode9.2
language: objective-c
script:
- xcodebuild clean build test -scheme Interval -only-testing:IntervalTests -enableCodeCoverage
  YES -derivedDataPath DerivedData clean build test
- xcrun llvm-cov report -instr-profile=$(find DerivedData/Build/ -name 'Coverage.profdata')
  DerivedData/Build/Products/Debug/Interval.app/Contents/MacOS/Interval

