osx_image: xcode9.2
language: objective-c
script:
- ./travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: s3
  bucket: snapshot.eight
  acl: public_read
  skip_cleanup: true

